contacts mob
KhelemeliaOleksii/SB-team-project pull request #17
Opened 2021-11-13 17:02 UTC by ZhylaA

2021-11-13 20:24 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
> +      <ul class="contacts-item__schedule list-no-ls">
Заміни contacts-item__schedule на contacts-item__schedule-list

2021-11-13 20:39 UTC, KhelemeliaOleksii requested changes
Тобі треба відцетрувати свої картинки, і підняти над секцією вгору

2021-11-13 20:42 UTC, ZhylaA commented on src/partials/contacts.html
> +      <ul class="contacts-item__schedule list-no-ls">
сделаю и вместе с 768 1200 пришлю

2021-11-13 22:55 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
>  <div class="container contacts-container">
Немає тега `<section class="section contacts-section">`і відповідно закриваючого тега вкінці

2021-11-13 22:58 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
> +    <ul class="contacts list-no-ls">
Додай клас `<ul class="contacts list-no-ls">` на <ul class="contacts__list list-no-ls">

2021-11-13 23:17 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
>  <div class="container contacts-container">
Потім в scss поставиш background-color

2021-11-13 23:17 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
> +    <ul class="contacts list-no-ls">
<ul class="contacts__list list-no-ls">

2021-11-13 23:17 UTC, KhelemeliaOleksii commented on src/partials/contacts.html
> +    <ul class="contacts list-no-ls">
`<ul class="contacts list-no-ls">`

2021-11-13 23:18 UTC, KhelemeliaOleksii commented on src/sass/layout/_contacts.scss
>    background: #fff5f6;
`background: #fff5f6;` на секцію

2021-11-13 23:20 UTC, KhelemeliaOleksii commented on src/sass/layout/_contacts.scss
> +  margin: 0 auto;
не треба`margin: 0 auto;`

2021-11-13 23:25 UTC, KhelemeliaOleksii commented on src/sass/layout/_contacts.scss
> +.contacts-wrap {
не потрібні стилі 
` margin: 0 auto;
  width: 100%;
  padding-left: 30px;
  padding-right: 30px;`

2021-11-13 23:28 UTC, KhelemeliaOleksii requested changes
Додатково: не вистачає риски після розкладу роботи

2021-11-14 08:35 UTC, ZhylaA commented on src/sass/layout/_contacts.scss
> +.contacts-wrap {
если я убираю margin: 0 auto; width: 100%; , то у меня все сдвигается в лево, а если оставляю то центрируется. Падинги по шаблону 50, 20 идет из контейнера и +30 из врапа и получается 50.

2021-11-14 08:36 UTC, ZhylaA commented on src/partials/contacts.html
> +    <ul class="contacts list-no-ls">
изменила

2021-11-14 08:36 UTC, ZhylaA commented on src/partials/contacts.html
>  <div class="container contacts-container">
добавила

2021-11-14 08:38 UTC, ZhylaA commented on src/sass/layout/_contacts.scss
>    background: #fff5f6;
+

2021-11-14 08:39 UTC, ZhylaA commented on src/sass/layout/_contacts.scss
> +  margin: 0 auto;
убрала

2021-11-14 16:26 UTC, KhelemeliaOleksii approved these changes

2021-11-14 16:26 UTC, merged